import os
import json
import glob
import argparse
import datetime
from typing import Dict, Any, List

import numpy as np
import pandas as pd
from openai import OpenAI
from utils import build_augmented_prompt, USER_INTENT_CATEGORIES


def formalize_openai_request(request_id: int, prompt: str) -> Dict[str, Any]:
    """Generates the structured OpenAI JSON request object for batch completion."""
    return {
        "custom_id": f"request_{request_id}",
        "method": "POST",
        "url": "/v1/chat/completions",
        "body": {
            "model": "gpt-4o",  # Updated target model string
            "response_format": {
                "type": "json_schema",
                "json_schema": {
                    "name": "intent_classification",
                    "strict": True,
                    "schema": {
                        "type": "object",
                        "properties": {
                            "reasoning": {"type": "string"},
                            "primary_intent": {
                                "type": "string",
                                "enum": USER_INTENT_CATEGORIES,
                            },
                            "secondary_intent": {
                                "type": "string",
                                "enum": USER_INTENT_CATEGORIES + ["Unassigned"],
                            },
                        },
                        "required": ["reasoning", "primary_intent", "secondary_intent"],
                        "additionalProperties": False
                    }
                }
            },
            "messages": [
                {
                    "role": "user",
                    "content": build_augmented_prompt(prompt)
                }
            ],
            "max_tokens": 1000,
        }
    }


class OpenAIHelper:
    def __init__(self, client: OpenAI):
        self.client = client

    def get_file_content(self, file_id: str) -> bytes:
        return self.client.files.content(file_id).content

    def get_batch(self, batch_id: str) -> Any:
        return self.client.batches.retrieve(batch_id)

    def create_batch(self, file_path: str) -> Any:
        with open(file_path, "rb") as file_obj:
            batch_input_file = self.client.files.create(
                file=file_obj,
                purpose="batch"
            )
        
        return self.client.batches.create(
            input_file_id=batch_input_file.id,
            endpoint="/v1/chat/completions",
            completion_window="24h",
            metadata={"description": "Intent Classification"}
        )


def extract_fields(content_str: str) -> Dict[str, Any]:
    """Safely parses JSON strings generated by structured outputs."""
    try:
        parsed = json.loads(content_str)
        return {
            "intent_cls_reasoning": parsed.get("reasoning"),
            "primary_intent": parsed.get("primary_intent"),
            "secondary_intent": parsed.get("secondary_intent")
        }
    except Exception:
        return {"intent_cls_reasoning": None, "primary_intent": None, "secondary_intent": None}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process OpenAI batch classification requests efficiently.")
    parser.add_argument("--input_file", type=str, default="data/search_arena_24k.jsonl", help="Path to input JSONL file.")
    parser.add_argument("--batch_data_dir", type=str, default="data/batches", help="Directory to save staging JSONL batch files.")
    parser.add_argument("--batch_size", type=int, default=40000, help="Chunk size constraint for batches (Max 50k rows).")
    parser.add_argument("--output_data_dir", type=str, default="data/output", help="Directory to save API outputs.")
    parser.add_argument("--cmd", type=str, required=True, choices=["data_prep", "launch", "postprocess"], help="Action pipeline step.")
    args = parser.parse_args()

    # Create directory infrastructure up front
    if args.batch_data_dir:
        os.makedirs(args.batch_data_dir, exist_ok=True)
    if args.output_data_dir:
        os.makedirs(args.output_data_dir, exist_ok=True)

    # -------------------------------------------------------------
    # Pipeline Command: Data Preparation
    # -------------------------------------------------------------
    if args.cmd == "data_prep":
        print(f"Loading staging file from: {args.input_file}...")
        data = pd.read_json(args.input_file, lines=True)
        
        # Safely capture first turn user query text
        data["prompt"] = data["messages_a"].apply(lambda x: x[0]["content"].strip() if isinstance(x, list) and len(x) > 0 else "")
        data["request_id"] = np.arange(len(data))
        
        print("Constructing structured batch frames payload formats...")
        records = data[["request_id", "prompt"]].to_dict(orient="records")
        data["request_json"] = [json.dumps(formalize_openai_request(r["request_id"], r["prompt"])) for r in records]

        # Splitting and chunk writing into batch file sets
        for i in range(0, len(data), args.batch_size):
            chunk = data["request_json"].iloc[i:i + args.batch_size]
            batch_file = os.path.join(args.batch_data_dir, f"batch_{i // args.batch_size}.jsonl")
            
            with open(batch_file, "w", encoding="utf-8") as f:
                f.write("\n".join(chunk) + "\n")
            print(f"Saved chunk slice to localized batch: {batch_file}")

    # -------------------------------------------------------------
    # Pipeline Command: Launch Batch Processing
    # -------------------------------------------------------------
    elif args.cmd == "launch":
        if not os.environ.get("OPENAI_API_KEY"):
            raise ValueError("OPENAI_API_KEY environment variable missing.")
            
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        openai_helper = OpenAIHelper(client)
        batch_info_data = []

        batch_files = glob.glob(os.path.join(args.batch_data_dir, "batch_*.jsonl"))
        if not batch_files:
            raise FileNotFoundError(f"No batch files detected under targeted pathway: {args.batch_data_dir}")

        for input_fname in batch_files:
            print(f"Uploading file and registering execution matrix for: {input_fname}...")
            batch_obj = openai_helper.create_batch(input_fname)
            batch_info_data.append(batch_obj.id)

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        batch_info_fname = os.path.join(args.output_data_dir, f"batch_info_{timestamp}.json")
        
        with open(batch_info_fname, "w", encoding="utf-8") as f:
            json.dump(batch_info_data, f, indent=4)
            
        print(f"Tracking identifiers saved to pipeline directory structural metadata: {batch_info_fname}")
        print("Required completion window takes up to ~24 hours. Re-run script step with --cmd postprocess afterwards.")

    # -------------------------------------------------------------
    # Pipeline Command: Postprocess & Assembly
    # -------------------------------------------------------------
    elif args.cmd == "postprocess":
        batch_info_files = glob.glob(os.path.join(args.output_data_dir, "batch_info_*.json"))
        if not batch_info_files:
            raise FileNotFoundError("Could not find configuration metadata tracker json file.")
            
        # Select latest tracked metadata footprint
        batch_info_file = max(batch_info_files, key=os.path.getctime)
        with open(batch_info_file, "r", encoding="utf-8") as f:
            batch_ids = json.load(f)

        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
        openai_helper = OpenAIHelper(client)
        
        all_results = []
        total_input_tokens = 0
        total_output_tokens = 0

        for idx, batch_id in enumerate(batch_ids):
            obj = openai_helper.get_batch(batch_id)
            print(f"Analyzing Job Status [{batch_id}]: {obj.status}")
            
            if obj.status != "completed":
                print(f"Skipping. Processing queue for batch state not reached resolution state: {obj.status}")
                continue
                
            output_file_id = obj.output_file_id
            if not output_file_id:
                error_file_id = obj.error_file_id
                err_content = openai_helper.get_file_content(error_file_id).decode("utf-8") if error_file_id else "No error trace ID."
                print(f"Failure logs trace content: {err_content}")
                raise RuntimeError(f"Processing error halted execution pipelines for target job frame {batch_id}")

            # Safe acquisition of payload bytes
            file_content = openai_helper.get_file_content(output_file_id)
            output_fname = os.path.join(args.output_data_dir, f"openai_output_batch_{idx}.jsonl")
            
            with open(output_fname, 'wb') as file:
                file.write(file_content)

            # High-performance processing of string payloads
            with open(output_fname, 'r', encoding="utf-8") as file:
                for line in file:
                    if not line.strip():
                        continue
                    res_obj = json.loads(line)
                    all_results.append(res_obj)
                    
                    # Accumulate operational telemetry metrics
                    usage = res_obj.get("response", {}).get("body", {}).get("usage", {})
                    total_input_tokens += usage.get("prompt_tokens", 0)
                    total_output_tokens += usage.get("completion_tokens", 0)

        if not all_results:
            print("No completed batch instances to parse.")
            exit(0)

        print("\nParsing structural classifications from output payload elements...")
        parsed_records = []
        for item in all_results:
            req_id = int(item["custom_id"].split("_")[1])
            content_str = item["response"]["body"]["choices"][0]["message"]["content"]
            extracted = extract_fields(content_str)
            extracted["request_id"] = req_id
            parsed_records.append(extracted)

        parsed_df = pd.DataFrame(parsed_records)
        input_df = pd.read_json(args.input_file, lines=True)
        input_df["request_id"] = np.arange(len(input_df))

        # Merge matching index records via strict map ID keys to guarantee matching sequence rows
        final_df = pd.merge(input_df, parsed_df, on="request_id", how="left").drop(columns=["request_id"])

        final_out_path = os.path.join(args.output_data_dir, "final_output.jsonl")
        final_df.to_json(final_out_path, orient="records", lines=True)
        
        print(f"Data mapping operation completed. Transformed file saved to target file location: {final_out_path}")
        print(f"Telemetry Info -> Input Tokens: {total_input_tokens} | Output Tokens: {total_output_tokens}")
        
        # Batch pricing updates structure
        estimated_cost = (0.50 * total_input_tokens + 2.00 * total_output_tokens) / 1e6
        print(f"Estimated Batch Price metric calculation context baseline: ${estimated_cost:.4f}")
